-- Sushi Shop Egypt full menu seed (150 dishes, 13 categories)
BEGIN;

DELETE FROM soshi.order_items;
DELETE FROM soshi.product_addons;
DELETE FROM soshi.banners;
DELETE FROM soshi.products;

DELETE FROM soshi.categories;

INSERT INTO soshi.categories (slug, name_ar, name_en, name_ru, sort_order)
VALUES
  ('soups', 'الشوربة', 'Soups', 'Супы', 1),
  ('uramaki', 'أوراماكي', 'Uramaki', 'Урамаки', 2),
  ('fried-rolls', 'المقلي', 'Fried Rolls', 'Жареные роллы', 3),
  ('cooked-rolls', 'المطبوخ', 'Cooked Rolls', 'Готовые роллы', 4),
  ('hosomaki', 'هوسوماكي', 'Hosomaki', 'Хосомаки', 5),
  ('nigiri-temaki-sashimi', 'نيجيري وتيماكي وساشيمي', 'Nigiri, Temaki & Sashimi', 'Нигири, Темаки и Сашими', 6),
  ('sets-combo', 'المجموعات والكومبو', 'Sets & Combo', 'Сеты и комбо', 7),
  ('salads', 'السلطات', 'Salads', 'Салаты', 8),
  ('noodles', 'النودلز', 'Noodles', 'Лапша', 9),
  ('appetizers', 'المقبلات', 'Appetizers', 'Закуски', 10),
  ('maki-large', 'ماكي كبير', 'Maki Large', 'Футомаки', 11),
  ('shawarma', 'الشاورما', 'Shawarma', 'Шаурма', 12),
  ('drinks', 'المشروبات', 'Drinks', 'Напитки', 13);

INSERT INTO soshi.products (
  name_ar, name_en, name_ru, price, category, is_available, sort_order,
  is_new, is_popular, is_offer, category_id
)
SELECT
  v.name_ar, v.name_en, v.name_ru, v.price, v.category, v.is_available, v.sort_order,
  v.is_new, v.is_popular, v.is_offer,
  c.id
FROM (VALUES
  ('شوربة ميسو', 'Miso Soup', 'Суп мисо', 150, 'soups', true, 1, false, false, false),
  ('شوربة إبي ميسو', 'Ebi Miso Soup', 'Суп эби мисо', 230, 'soups', true, 2, false, false, false),
  ('شوربة توم يم', 'Tom Yum Soup', 'Суп том ям', 250, 'soups', true, 3, false, false, false),
  ('شوربة مأكولات بحرية كريمية', 'Creamy Seafood Soup', 'Кремовый морской суп', 280, 'soups', true, 4, false, false, false),
  ('شوربة رامن', 'Ramen Soup', 'Суп рамен', 300, 'soups', true, 5, false, false, false),
  ('شوربة سوشي شوب الخاصة', 'Sushi Shop Special Soup', 'Фирменный суп Sushi Shop', 300, 'soups', true, 6, false, false, false),
  ('توم يم مع أرز', 'Tom Yum with Rice', 'Том ям с рисом', 300, 'soups', true, 7, false, false, false),
  ('رول مكسيكو', 'Mexico Roll', 'Ролл Мексика', 350, 'uramaki', true, 1, false, false, false),
  ('كاليفورنيا ماساجو', 'California Masago', 'Калифорния масаго', 420, 'uramaki', true, 2, false, false, false),
  ('رول جامايكا', 'Jamaica Roll', 'Ролл Ямайка', 330, 'uramaki', true, 3, false, false, false),
  ('رول الهرم', 'Pyramid Roll', 'Ролл Пирамида', 370, 'uramaki', true, 4, false, false, false),
  ('رول جمبري', 'Shrimp Roll', 'Ролл с креветкой', 290, 'uramaki', true, 5, false, false, false),
  ('فيلادلفيا جمبري', 'Philadelphia Shrimp Roll', 'Филадельфия с креветкой', 370, 'uramaki', true, 6, false, false, false),
  ('ديناميت سلمون', 'Dynamite Salmon Roll', 'Динамит с лососем', 350, 'uramaki', true, 7, false, false, false),
  ('رول بانزاي', 'Banzai Roll', 'Ролл Банзай', 390, 'uramaki', true, 8, false, false, false),
  ('رول رولينز', 'Rollins Roll', 'Ролл Роллинс', 350, 'uramaki', true, 9, false, false, false),
  ('سلمون كريمي', 'Creamy Salmon Roll', 'Кремовый лосось', 290, 'uramaki', true, 10, false, false, false),
  ('رول رومانتيك', 'Romantic Roll', 'Ролл Романтик', 300, 'uramaki', true, 11, false, false, false),
  ('رول قوس قزح', 'Rainbow Roll', 'Ролл Радуга', 360, 'uramaki', true, 12, false, false, false),
  ('كاليفورنيا كلاسيك', 'California Classic Roll', 'Калифорния классик', 330, 'uramaki', true, 13, false, false, false),
  ('رول سوشي شوب السري', 'Secret Sushi Shop Roll', 'Секретный ролл Sushi Shop', 270, 'uramaki', true, 14, false, false, false),
  ('رول الفراشة الخاص', 'Sushi Shop Special Butterfly Roll', 'Фирменный ролл Бабочка', 370, 'uramaki', true, 15, false, false, false),
  ('ماكي سلمون', 'Salmon Maki', 'Маки с лососем', 310, 'uramaki', true, 16, false, false, false),
  ('رول النمر الوردي', 'Pink Panther Roll', 'Ролл Розовая пантера', 250, 'uramaki', true, 17, false, false, false),
  ('ديناميت تونة كريمية', 'Dynamite Creamy Tuna Roll', 'Динамит с тунцом кремовый', 380, 'uramaki', true, 18, false, false, false),
  ('كاليفورنيا سلمون', 'California Salmon Roll', 'Калифорния с лососем', 340, 'uramaki', true, 19, false, false, false),
  ('رول نيويورك', 'New York Roll', 'Ролл Нью-Йорк', 360, 'uramaki', true, 20, false, false, false),
  ('جمبري كريمي', 'Creamy Shrimp Roll', 'Кремовая креветка', 350, 'uramaki', true, 21, false, false, false),
  ('كندا لوكس', 'Canada Lux Roll', 'Канада Люкс', 380, 'uramaki', true, 22, false, false, false),
  ('فيلادلفيا كلاسيك', 'Philadelphia Classic Roll', 'Филадельфия классик', 280, 'uramaki', true, 23, false, false, false),
  ('رول سيزر', 'Caesar Roll', 'Ролл Цезарь', 190, 'uramaki', true, 24, false, false, false),
  ('رول رينا سلمون مدخن', 'Reina Roll Smoked Salmon', 'Ролл Рейна копчёный лосось', 360, 'uramaki', true, 25, false, false, false),
  ('فيلادلفيا تونة', 'Philadelphia Tuna Roll', 'Филадельфия с тунцом', 380, 'uramaki', true, 26, false, false, false),
  ('رول التنين الأسود', 'Black Dragon Roll', 'Ролл Чёрный дракон', 400, 'uramaki', true, 27, false, false, false),
  ('ديناميت سلمون كريمي', 'Dynamite Creamy Salmon Roll', 'Динамит кремовый лосось', 380, 'uramaki', true, 28, false, false, false),
  ('ديناميت تونة', 'Dynamite Tuna Roll', 'Динамит с тунцом', 330, 'uramaki', true, 29, false, false, false),
  ('كاليفورنيا جمبري', 'California Shrimp Roll', 'Калифорния с креветкой', 365, 'uramaki', true, 30, false, false, false),
  ('فيلادلفيا أنقليس', 'Philadelphia Eel Roll', 'Филадельфия с угрём', 380, 'uramaki', true, 31, false, false, false),
  ('سلمون مانيا', 'Salmon Mania Roll', 'Салмон Мания', 210, 'fried-rolls', true, 1, false, false, false),
  ('هامانيشي', 'Hamanishi Roll', 'Хаманиши', 300, 'fried-rolls', true, 2, false, false, false),
  ('جولدن أميزينج', 'Golden Amazing Roll', 'Голден Амейзинг', 290, 'fried-rolls', true, 3, false, false, false),
  ('كرانشي سلمون', 'Crunchy Salmon Roll', 'Хрустящий лосось', 220, 'fried-rolls', true, 4, false, false, false),
  ('هوت ليمون', 'Hot Lemon Roll', 'Хот Лимон', 295, 'fried-rolls', true, 5, false, false, false),
  ('سبايدر هوت', 'Spider Hot Roll', 'Спайдер хот', 230, 'fried-rolls', true, 6, false, false, false),
  ('رول الملكة', 'Queen Roll', 'Ролл Королева', 240, 'fried-rolls', true, 7, false, false, false),
  ('تيكا هوت', 'Tika Hot Roll', 'Тика хот', 205, 'fried-rolls', true, 8, false, false, false),
  ('فولكانو فيلادلفيا', 'Volcano Philadelphia', 'Вулкан Филадельфия', 350, 'fried-rolls', true, 9, false, false, false),
  ('ساكي سان هوت', 'Sake San Hot Roll', 'Саке Сан хот', 270, 'fried-rolls', true, 10, false, false, false),
  ('صحراء سلمون', 'Sahara Roll Salmon', 'Сахара с лососем', 230, 'fried-rolls', true, 11, false, false, false),
  ('تونا سان هوت', 'Tuna San Hot Roll', 'Туна Сан хот', 235, 'fried-rolls', true, 12, false, false, false),
  ('أكينو هوت', 'Akeno Hot Roll', 'Акено хот', 280, 'fried-rolls', true, 13, false, false, false),
  ('أياشي', 'Ayashi Roll', 'Аяши', 350, 'fried-rolls', true, 14, false, false, false),
  ('كرانشي تونة', 'Crunchy Tuna Roll', 'Хрустящий тунец', 270, 'fried-rolls', true, 15, false, false, false),
  ('كرانشي جمبري هوت', 'Crunchy Shrimp Hot Roll', 'Хрустящая креветка хот', 240, 'fried-rolls', true, 16, false, false, false),
  ('دبل سلمون', 'Double Salmon Roll', 'Двойной лосось', 350, 'cooked-rolls', true, 1, false, false, false),
  ('كراكر', 'Cracker Roll', 'Крекер', 310, 'cooked-rolls', true, 2, false, false, false),
  ('زين', 'Zen Roll', 'Дзен', 320, 'cooked-rolls', true, 3, false, false, false),
  ('موناليزا', 'Mona Lisa Roll', 'Мона Лиза', 350, 'cooked-rolls', true, 4, false, false, false),
  ('ساكي', 'Saki Roll', 'Саки', 340, 'cooked-rolls', true, 5, false, false, false),
  ('فينوم مقلي', 'Vienom Fried Roll', 'Вьеном жареный', 320, 'cooked-rolls', true, 6, false, false, false),
  ('لافا مقلي', 'Lava Fried Roll', 'Лава жареный', 350, 'cooked-rolls', true, 7, false, false, false),
  ('جوهرة', 'Jewel Roll', 'Джуэл', 300, 'cooked-rolls', true, 8, false, false, false),
  ('فلامينج', 'Flaming Roll', 'Флейминг', 320, 'cooked-rolls', true, 9, false, false, false),
  ('توبيكو', 'Tobiko Roll', 'Тобико', 330, 'cooked-rolls', true, 10, false, false, false),
  ('هوسوماكي كافيار', 'Hosomaki Caviar', 'Хосомаки икра', 220, 'hosomaki', true, 1, false, false, false),
  ('هوسوماكي خيار', 'Hosomaki Cucumber', 'Хосомаки огурец', 80, 'hosomaki', true, 2, false, false, false),
  ('هوسوماكي رنجة', 'Hosomaki with Herring', 'Хосомаки селёдка', 220, 'hosomaki', true, 3, false, false, false),
  ('هوسوماكي سلمون', 'Hosomaki Salmon', 'Хосомаки лосось', 220, 'hosomaki', true, 4, false, false, false),
  ('هوسوماكي جمبري', 'Hosomaki Shrimp', 'Хосомаки креветка', 220, 'hosomaki', true, 5, false, false, false),
  ('هوسوماكي أنقليس', 'Hosomaki Eel', 'Хосомаки угорь', 190, 'hosomaki', true, 6, false, false, false),
  ('هوسوماكي كابوريا', 'Hosomaki Crab', 'Хосомаки краб', 150, 'hosomaki', true, 7, false, false, false),
  ('هوسوماكي أفوكادو', 'Hosomaki Avocado', 'Хосомаки авокадо', 130, 'hosomaki', true, 8, false, false, false),
  ('هوسوماكي تونة', 'Hosomaki Tuna', 'Хосомаки тунец', 220, 'hosomaki', true, 9, false, false, false),
  ('نيجيري أخطبوط', 'Nigiri Octopus', 'Нигири осьминог', 50, 'nigiri-temaki-sashimi', true, 1, false, false, false),
  ('نيجيري تونة', 'Nigiri Tuna', 'Нигири тунец', 50, 'nigiri-temaki-sashimi', true, 2, false, false, false),
  ('نيجيري سلمون', 'Nigiri Salmon', 'Нигири лосось', 50, 'nigiri-temaki-sashimi', true, 3, false, false, false),
  ('نيجيري جمبري', 'Nigiri Shrimp', 'Нигири креветка', 50, 'nigiri-temaki-sashimi', true, 4, false, false, false),
  ('نيجيري كابوريا', 'Nigiri Crab', 'Нигири краб', 50, 'nigiri-temaki-sashimi', true, 5, false, false, false),
  ('جمبري تمبورا', 'Shrimp Tempura', 'Креветка темпура', 50, 'nigiri-temaki-sashimi', true, 6, false, false, false),
  ('نيجيري أنقليس', 'Nigiri Eel', 'Нигири угорь', 50, 'nigiri-temaki-sashimi', true, 7, false, false, false),
  ('ساشيمي ماغورو', 'Maguro Sashimi', 'Сашими магуро', 275, 'nigiri-temaki-sashimi', true, 8, false, false, false),
  ('ساشيمي أكتو', 'Tako Sashimi', 'Сашими тако', 290, 'nigiri-temaki-sashimi', true, 9, false, false, false),
  ('ساشيمي ساكي', 'Sake Sashimi', 'Сашими саке', 265, 'nigiri-temaki-sashimi', true, 10, false, false, false),
  ('ساشيمي سوشي شوب', 'Sushi Shop Sashimi', 'Сашими Sushi Shop', 1500, 'nigiri-temaki-sashimi', true, 11, false, false, false),
  ('تيماكي سلمون', 'Temaki Salmon', 'Темаки лосось', 180, 'nigiri-temaki-sashimi', true, 12, false, false, false),
  ('تيماكي تونة', 'Temaki Tuna', 'Темаки тунец', 180, 'nigiri-temaki-sashimi', true, 13, false, false, false),
  ('تيماكي جمبري', 'Temaki Shrimp', 'Темаки креветка', 180, 'nigiri-temaki-sashimi', true, 14, false, false, false),
  ('تيماكي سوشي شوب الخاص', 'Sushi Shop Special Temaki', 'Фирменный темаки', 250, 'nigiri-temaki-sashimi', true, 15, false, false, false),
  ('تيماكي أنقليس', 'Temaki Eel', 'Темаки угорь', 180, 'nigiri-temaki-sashimi', true, 16, false, false, false),
  ('كيك 50 قطعة', 'Cake 50 Pcs', 'Торт 50 шт', 2000, 'sets-combo', true, 1, true, false, false),
  ('كيك 48 قطعة', 'Cake 48 Pcs', 'Торт 48 шт', 1750, 'sets-combo', true, 2, false, false, false),
  ('كيك 32 قطعة', 'Cake 32 Pcs', 'Торт 32 шт', 1500, 'sets-combo', true, 3, false, false, false),
  ('كومبو مقلي 40', 'Fried Combo 40 Pcs', 'Жареное комбо 40', 1400, 'sets-combo', true, 4, false, false, false),
  ('فوياج 100', 'Voyage Combo 100', 'Вояж 100', 3700, 'sets-combo', true, 5, false, false, false),
  ('كومبو 14 سبيشال 3', 'Combo 14 Special 3', 'Комбо 14 спешл 3', 490, 'sets-combo', true, 6, false, false, false),
  ('كومبو 12', 'Kombo 12 Pcs', 'Комбо 12', 500, 'sets-combo', true, 7, false, false, false),
  ('ميكس 40', 'Mix 40', 'Микс 40', 1250, 'sets-combo', true, 8, false, false, false),
  ('جولدن 40', 'Golden Combo 40', 'Голден 40', 1400, 'sets-combo', true, 9, false, false, false),
  ('كومبو 14 مقلي', 'Combo 14 Fried', 'Комбо 14 жареное', 680, 'sets-combo', true, 10, false, false, false),
  ('فيلادلفيا لوز 40', 'Philadelphia Almond 40', 'Филадельфия миндаль 40', 1400, 'sets-combo', true, 11, false, false, false),
  ('ريتش 24', 'Rich Combo 24', 'Рич 24', 1100, 'sets-combo', true, 12, false, false, false),
  ('كومبو 20 ميكس', 'Combo 20 Mix', 'Комбо 20 микс', 650, 'sets-combo', true, 13, false, false, false),
  ('ريلاكس 50', 'Relax Combo 50', 'Релакс 50', 1600, 'sets-combo', true, 14, false, false, false),
  ('شريمب لافر 13', 'Shrimp Lover Combo 13', 'Шримп лавер 13', 620, 'sets-combo', true, 15, false, false, false),
  ('كومبو ويسو 40', 'Combo WESO 40', 'Комбо WESO 40', 1400, 'sets-combo', true, 16, true, false, false),
  ('لايت 15', 'Light Combo 15', 'Лайт 15', 700, 'sets-combo', true, 17, false, false, false),
  ('كومبو 14 سبيشال 2', 'Combo 14 Special 2', 'Комбо 14 спешл 2', 520, 'sets-combo', true, 18, false, false, false),
  ('كومبو 20 ني', 'Combo 20 Raw', 'Комбо 20 сырое', 820, 'sets-combo', true, 19, false, false, false),
  ('ألور 25', 'Allure Combo 25', 'Аллюр 25', 1050, 'sets-combo', true, 20, false, false, false),
  ('تونا لافر 13', 'Tuna Lover 13', 'Туна лавер 13', 650, 'sets-combo', true, 21, false, false, false),
  ('كومبو 24 مقلي', 'Combo 24 Fried', 'Комбо 24 жареное', 1000, 'sets-combo', true, 22, false, false, false),
  ('فورتشن 75', 'Fortune Combo 75', 'Форчун 75', 2600, 'sets-combo', true, 23, true, false, false),
  ('كومبو 14 سبيشال 1', 'Kombo 14 Special 1', 'Комбо 14 спешл 1', 470, 'sets-combo', true, 24, false, false, false),
  ('كومبو ماين 20', 'Combo Mine 20', 'Комбо майн 20', 800, 'sets-combo', true, 25, false, false, false),
  ('كومبو 20 مقلي', 'Kombo 20 Fried', 'Комбо 20 жареное', 840, 'sets-combo', true, 26, false, false, false),
  ('كومبو إكسكويز 16', 'Combo Exquis 16', 'Комбо экскиз 16', 750, 'sets-combo', true, 27, false, false, false),
  ('كومبو أسبشل 30', 'Combo Aspshel 30 Bes', 'Комбо асбшел 30', 1200, 'sets-combo', true, 28, false, false, false),
  ('أولد سكول 40', 'Old School Combo 40', 'Олд скул 40', 1450, 'sets-combo', true, 29, false, false, false),
  ('هوسوماكي كومبو 30', 'Hosomaki Combo 30', 'Хосомаки комбо 30', 900, 'sets-combo', true, 30, false, false, false),
  ('سلطة تاكو', 'Taco Salad', 'Салат тако', 300, 'salads', true, 1, false, false, false),
  ('سلطة خضار', 'Vegetable Salad', 'Овощной салат', 100, 'salads', true, 2, false, false, false),
  ('سلطة يوناني', 'Greek Salad', 'Греческий салат', 180, 'salads', true, 3, false, false, false),
  ('سلطة كابوريا', 'Crab Salad', 'Крабовый салат', 250, 'salads', true, 4, false, false, false),
  ('بوكي بول', 'Poke Bowl', 'Поке боул', 50, 'salads', true, 5, false, false, false),
  ('سلطة سلمون يابانية', 'Salmon Japanese Salad', 'Японский салат с лососем', 410, 'salads', true, 6, true, false, false),
  ('بوكي بالجمبري', 'Poke with Shrimp', 'Поке с креветкой', 300, 'salads', true, 7, false, false, false),
  ('بوكي بالسلمون', 'Poke with Salmon', 'Поке с лососем', 350, 'salads', true, 8, false, false, false),
  ('سلطة التنين', 'Dragon Salad', 'Салат Дракон', 300, 'salads', true, 9, false, false, false),
  ('سلطة سلمون أفوكادو', 'Salmon Avocado Salad', 'Салат лосось авокадо', 300, 'salads', true, 10, false, false, false),
  ('سلطة سلمون كرانشي', 'Crunchy Salmon Salad', 'Хрустящий салат с лососем', 350, 'salads', true, 11, false, false, false),
  ('سلطة أعشاب بحرية', 'Seaweed Salad', 'Салат из водорослей', 250, 'salads', true, 12, false, false, false),
  ('نودلز فراخ', 'Noodles Chicken', 'Лапша с курицей', 250, 'noodles', true, 1, false, false, false),
  ('نودلز جمبري', 'Noodles Shrimp', 'Лапша с креветкой', 300, 'noodles', true, 2, false, false, false),
  ('نودلز لحم', 'Noodles Beef', 'Лапша с говядиной', 270, 'noodles', true, 3, false, false, false),
  ('نودلز خضار', 'Noodles Vegetables', 'Лапша с овощами', 200, 'noodles', true, 4, false, false, false),
  ('جمبري تايجر', 'Shrimp Tiger', 'Креветка тигр', 280, 'appetizers', true, 1, false, false, false),
  ('بطاطس مقلية', 'French Fries', 'Картофель фри', 100, 'appetizers', true, 2, false, false, false),
  ('سبرينج رول جبنة', 'Cheese Spring Rolls', 'Спринг-роллы с сыром', 130, 'appetizers', true, 3, false, false, false),
  ('سبرينج رول جمبري', 'Shrimp Spring', 'Спринг-роллы с креветкой', 290, 'appetizers', true, 4, false, false, false),
  ('موتزاريلا ستيك', 'Mozzarella Sticks', 'Палочки моцарелла', 120, 'appetizers', true, 5, false, false, false),
  ('بونبون جبنة', 'Cheese Bonbon', 'Сырные бонбоны', 250, 'appetizers', true, 6, false, false, false),
  ('سبرينج رول سوشي شوب', 'Sushi Shop Spring Rolls', 'Спринг-роллы Sushi Shop', 290, 'appetizers', true, 7, false, false, false),
  ('سبرينج رول خضار', 'Vegetables Spring Rolls', 'Овощные спринг-роллы', 100, 'appetizers', true, 8, false, false, false),
  ('فوتوماكي', 'Futomaki', 'Футомаки', 430, 'maki-large', true, 1, true, false, false),
  ('شاورما فراخ مع صوص الجبنة والبطاطس', 'Chicken Shawarma with Cheese Sauce & Fries', 'Шаурма с сырным соусом и картофелем', 120, 'shawarma', true, 1, false, false, false),
  ('شاورما فراخ مع صوص الجبنة', 'Chicken Shawarma with Cheese Sauce', 'Шаурма с сырным соусом', 105, 'shawarma', true, 2, false, false, false),
  ('شاورما فراخ كلاسيك', 'Classic Chicken Shawarma', 'Классическая куриная шаурма', 90, 'shawarma', true, 3, false, false, false),
  ('فتة شاورما فراخ', 'Chicken Shawarma Fatteh', 'Фатте с шаурмой', 120, 'shawarma', true, 4, false, false, false),
  ('شاورما فراخ مع صوص الباربكيو', 'Chicken Shawarma with BBQ Sauce', 'Шаурма с BBQ соусом', 100, 'shawarma', true, 5, false, false, false),
  ('كولا', 'Cola', 'Кола', 25, 'drinks', true, 1, false, false, false)
) AS v(name_ar, name_en, name_ru, price, category, is_available, sort_order, is_new, is_popular, is_offer)
JOIN soshi.categories c ON c.slug = v.category;

COMMIT;

SELECT c.slug, c.name_en, COUNT(p.id) AS dishes
FROM soshi.categories c
LEFT JOIN soshi.products p ON p.category_id = c.id
GROUP BY c.slug, c.name_en, c.sort_order
ORDER BY c.sort_order;

