INSERT INTO soshi.products (name_ar, name_en, name_ru, price, category, is_available, sort_order, is_new, is_popular, is_offer, category_id)
SELECT v.name_ar, v.name_en, v.name_ru, v.price, v.category, v.is_available, v.sort_order, v.is_new, v.is_popular, v.is_offer, c.id
FROM (VALUES
('شوربة ميسو', 'Miso Soup', 'Суп мисо', 150, 'soups', true, 1, false, false, false),
('شوربة إبي ميسو', 'Ebi Miso Soup', 'Суп эби мисо', 230, 'soups', true, 2, false, false, false),
('شوربة توم يم', 'Tom Yum Soup', 'Суп том ям', 250, 'soups', true, 3, false, false, false),
('شوربة مأكولات بحرية كريمية', 'Creamy Seafood Soup', 'Кремовый морской суп', 280, 'soups', true, 4, false, false, false),
('شوربة رامن', 'Ramen Soup', 'Суп рамен', 300, 'soups', true, 5, false, false, false),
('شوربة سوشي شوب الخاصة', 'Sushi Shop Special Soup', 'Фирменный суп Sushi Shop', 300, 'soups', true, 6, false, false, false),
('توم يم مع أرز', 'Tom Yum with Rice', 'Том ям с рисом', 300, 'soups', true, 7, false, false, false),
('رول مكسيكو', 'Mexico Roll', 'Ролл Мексика', 350, 'uramaki', true, 1, false, false, false),
('كاليفورنيا ماساجو', 'California Masago', 'Калифорния масаго', 420, 'uramaki', true, 2, false, false, false),
('رول جامايكا', 'Jamaica Roll', 'Ролл Ямайка', 330, 'uramaki', true, 3, false, false, false),
('رول الهرم', 'Pyramid Roll', 'Ролл Пирамида', 370, 'uramaki', true, 4, false, false, false),
('رول جمبري', 'Shrimp Roll', 'Ролл с креветкой', 290, 'uramaki', true, 5, false, false, false),
('فيلادلفيا جمبري', 'Philadelphia Shrimp Roll', 'Филадельфия с креветкой', 370, 'uramaki', true, 6, false, false, false),
('ديناميت سلمون', 'Dynamite Salmon Roll', 'Динамит с лососем', 350, 'uramaki', true, 7, false, false, false),
('رول بانزاي', 'Banzai Roll', 'Ролл Банзай', 390, 'uramaki', true, 8, false, false, false),
('رول رولينز', 'Rollins Roll', 'Ролл Роллинс', 350, 'uramaki', true, 9, false, false, false),
('سلمون كريمي', 'Creamy Salmon Roll', 'Кремовый лосось', 290, 'uramaki', true, 10, false, false, false),
('رول رومانتيك', 'Romantic Roll', 'Ролл Романтик', 300, 'uramaki', true, 11, false, false, false),
('رول قوس قزح', 'Rainbow Roll', 'Ролл Радуга', 360, 'uramaki', true, 12, false, false, false),
('كاليفورنيا كلاسيك', 'California Classic Roll', 'Калифорния классик', 330, 'uramaki', true, 13, false, false, false),
('رول سوشي شوب السري', 'Secret Sushi Shop Roll', 'Секретный ролл Sushi Shop', 270, 'uramaki', true, 14, false, false, false),
('رول الفراشة الخاص', 'Sushi Shop Special Butterfly Roll', 'Фирменный ролл Бабочка', 370, 'uramaki', true, 15, false, false, false),
('ماكي سلمون', 'Salmon Maki', 'Маки с лососем', 310, 'uramaki', true, 16, false, false, false),
('رول النمر الوردي', 'Pink Panther Roll', 'Ролл Розовая пантера', 250, 'uramaki', true, 17, false, false, false),
('ديناميت تونة كريمية', 'Dynamite Creamy Tuna Roll', 'Динамит с тунцом кремовый', 380, 'uramaki', true, 18, false, false, false),
('كاليفورنيا سلمون', 'California Salmon Roll', 'Калифорния с лососем', 340, 'uramaki', true, 19, false, false, false),
('رول نيويورك', 'New York Roll', 'Ролл Нью-Йорк', 360, 'uramaki', true, 20, false, false, false),
('جمبري كريمي', 'Creamy Shrimp Roll', 'Кремовая креветка', 350, 'uramaki', true, 21, false, false, false),
('كندا لوكس', 'Canada Lux Roll', 'Канада Люкс', 380, 'uramaki', true, 22, false, false, false),
('فيلادلفيا كلاسيك', 'Philadelphia Classic Roll', 'Филадельфия классик', 280, 'uramaki', true, 23, false, false, false),
('رول سيزر', 'Caesar Roll', 'Ролл Цезарь', 190, 'uramaki', true, 24, false, false, false),
('رول رينا سلمون مدخن', 'Reina Roll Smoked Salmon', 'Ролл Рейна копчёный лосось', 360, 'uramaki', true, 25, false, false, false),
('فيلادلفيا تونة', 'Philadelphia Tuna Roll', 'Филадельфия с тунцом', 380, 'uramaki', true, 26, false, false, false),
('رول التنين الأسود', 'Black Dragon Roll', 'Ролл Чёрный дракон', 400, 'uramaki', true, 27, false, false, false),
('ديناميت سلمون كريمي', 'Dynamite Creamy Salmon Roll', 'Динамит кремовый лосось', 380, 'uramaki', true, 28, false, false, false),
('ديناميت تونة', 'Dynamite Tuna Roll', 'Динамит с тунцом', 330, 'uramaki', true, 29, false, false, false),
('كاليفورنيا جمبري', 'California Shrimp Roll', 'Калифорния с креветкой', 365, 'uramaki', true, 30, false, false, false),
('فيلادلفيا أنقليس', 'Philadelphia Eel Roll', 'Филадельфия с угрём', 380, 'uramaki', true, 31, false, false, false),
('سلمون مانيا', 'Salmon Mania Roll', 'Салмон Мания', 210, 'fried-rolls', true, 1, false, false, false),
('هامانيشي', 'Hamanishi Roll', 'Хаманиши', 300, 'fried-rolls', true, 2, false, false, false)
) AS v(name_ar, name_en, name_ru, price, category, is_available, sort_order, is_new, is_popular, is_offer)
JOIN soshi.categories c ON c.slug = v.category;