INSERT INTO soshi.products (name_ar, name_en, name_ru, price, category, is_available, sort_order, is_new, is_popular, is_offer, category_id)
SELECT v.name_ar, v.name_en, v.name_ru, v.price, v.category, v.is_available, v.sort_order, v.is_new, v.is_popular, v.is_offer, c.id
FROM (VALUES
('ساشيمي ماغورو', 'Maguro Sashimi', 'Сашими магуро', 275, 'nigiri-temaki-sashimi', true, 8, false, false, false),
('ساشيمي أكتو', 'Tako Sashimi', 'Сашими тако', 290, 'nigiri-temaki-sashimi', true, 9, false, false, false),
('ساشيمي ساكي', 'Sake Sashimi', 'Сашими саке', 265, 'nigiri-temaki-sashimi', true, 10, false, false, false),
('ساشيمي سوشي شوب', 'Sushi Shop Sashimi', 'Сашими Sushi Shop', 1500, 'nigiri-temaki-sashimi', true, 11, false, false, false),
('تيماكي سلمون', 'Temaki Salmon', 'Темаки лосось', 180, 'nigiri-temaki-sashimi', true, 12, false, false, false),
('تيماكي تونة', 'Temaki Tuna', 'Темаки тунец', 180, 'nigiri-temaki-sashimi', true, 13, false, false, false),
('تيماكي جمبري', 'Temaki Shrimp', 'Темаки креветка', 180, 'nigiri-temaki-sashimi', true, 14, false, false, false),
('تيماكي سوشي شوب الخاص', 'Sushi Shop Special Temaki', 'Фирменный темаки', 250, 'nigiri-temaki-sashimi', true, 15, false, false, false),
('تيماكي أنقليس', 'Temaki Eel', 'Темаки угорь', 180, 'nigiri-temaki-sashimi', true, 16, false, false, false),
('كيك 50 قطعة', 'Cake 50 Pcs', 'Торт 50 шт', 2000, 'sets-combo', true, 1, true, false, false),
('كيك 48 قطعة', 'Cake 48 Pcs', 'Торт 48 шт', 1750, 'sets-combo', true, 2, false, false, false),
('كيك 32 قطعة', 'Cake 32 Pcs', 'Торт 32 шт', 1500, 'sets-combo', true, 3, false, false, false),
('كومبو مقلي 40', 'Fried Combo 40 Pcs', 'Жареное комбо 40', 1400, 'sets-combo', true, 4, false, false, false),
('فوياج 100', 'Voyage Combo 100', 'Вояж 100', 3700, 'sets-combo', true, 5, false, false, false),
('كومبو 14 سبيشال 3', 'Combo 14 Special 3', 'Комбо 14 спешл 3', 490, 'sets-combo', true, 6, false, false, false),
('كومبو 12', 'Kombo 12 Pcs', 'Комбо 12', 500, 'sets-combo', true, 7, false, false, false),
('ميكس 40', 'Mix 40', 'Микс 40', 1250, 'sets-combo', true, 8, false, false, false),
('جولدن 40', 'Golden Combo 40', 'Голден 40', 1400, 'sets-combo', true, 9, false, false, false),
('كومبو 14 مقلي', 'Combo 14 Fried', 'Комбо 14 жареное', 680, 'sets-combo', true, 10, false, false, false),
('فيلادلفيا لوز 40', 'Philadelphia Almond 40', 'Филадельфия миндаль 40', 1400, 'sets-combo', true, 11, false, false, false),
('ريتش 24', 'Rich Combo 24', 'Рич 24', 1100, 'sets-combo', true, 12, false, false, false),
('كومبو 20 ميكس', 'Combo 20 Mix', 'Комбо 20 микс', 650, 'sets-combo', true, 13, false, false, false),
('ريلاكس 50', 'Relax Combo 50', 'Релакс 50', 1600, 'sets-combo', true, 14, false, false, false),
('شريمب لافر 13', 'Shrimp Lover Combo 13', 'Шримп лавер 13', 620, 'sets-combo', true, 15, false, false, false),
('كومبو ويسو 40', 'Combo WESO 40', 'Комбо WESO 40', 1400, 'sets-combo', true, 16, true, false, false),
('لايت 15', 'Light Combo 15', 'Лайт 15', 700, 'sets-combo', true, 17, false, false, false),
('كومبو 14 سبيشال 2', 'Combo 14 Special 2', 'Комбо 14 спешл 2', 520, 'sets-combo', true, 18, false, false, false),
('كومبو 20 ني', 'Combo 20 Raw', 'Комбо 20 сырое', 820, 'sets-combo', true, 19, false, false, false),
('ألور 25', 'Allure Combo 25', 'Аллюр 25', 1050, 'sets-combo', true, 20, false, false, false),
('تونا لافر 13', 'Tuna Lover 13', 'Туна лавер 13', 650, 'sets-combo', true, 21, false, false, false),
('كومبو 24 مقلي', 'Combo 24 Fried', 'Комбо 24 жареное', 1000, 'sets-combo', true, 22, false, false, false),
('فورتشن 75', 'Fortune Combo 75', 'Форчун 75', 2600, 'sets-combo', true, 23, true, false, false),
('كومبو 14 سبيشال 1', 'Kombo 14 Special 1', 'Комбо 14 спешл 1', 470, 'sets-combo', true, 24, false, false, false),
('كومبو ماين 20', 'Combo Mine 20', 'Комбо майн 20', 800, 'sets-combo', true, 25, false, false, false),
('كومبو 20 مقلي', 'Kombo 20 Fried', 'Комбо 20 жареное', 840, 'sets-combo', true, 26, false, false, false),
('كومبو إكسكويز 16', 'Combo Exquis 16', 'Комбо экскиз 16', 750, 'sets-combo', true, 27, false, false, false),
('كومبو أسبشل 30', 'Combo Aspshel 30 Bes', 'Комбо асбшел 30', 1200, 'sets-combo', true, 28, false, false, false),
('أولد سكول 40', 'Old School Combo 40', 'Олд скул 40', 1450, 'sets-combo', true, 29, false, false, false),
('هوسوماكي كومبو 30', 'Hosomaki Combo 30', 'Хосомаки комбо 30', 900, 'sets-combo', true, 30, false, false, false),
('سلطة تاكو', 'Taco Salad', 'Салат тако', 300, 'salads', true, 1, false, false, false)
) AS v(name_ar, name_en, name_ru, price, category, is_available, sort_order, is_new, is_popular, is_offer)
JOIN soshi.categories c ON c.slug = v.category;