INSERT INTO soshi.products (name_ar, name_en, name_ru, price, category, is_available, sort_order, is_new, is_popular, is_offer, category_id)
SELECT v.name_ar, v.name_en, v.name_ru, v.price, v.category, v.is_available, v.sort_order, v.is_new, v.is_popular, v.is_offer, c.id
FROM (VALUES
('جولدن أميزينج', 'Golden Amazing Roll', 'Голден Амейзинг', 290, 'fried-rolls', true, 3, false, false, false),
('كرانشي سلمون', 'Crunchy Salmon Roll', 'Хрустящий лосось', 220, 'fried-rolls', true, 4, false, false, false),
('هوت ليمون', 'Hot Lemon Roll', 'Хот Лимон', 295, 'fried-rolls', true, 5, false, false, false),
('سبايدر هوت', 'Spider Hot Roll', 'Спайдер хот', 230, 'fried-rolls', true, 6, false, false, false),
('رول الملكة', 'Queen Roll', 'Ролл Королева', 240, 'fried-rolls', true, 7, false, false, false),
('تيكا هوت', 'Tika Hot Roll', 'Тика хот', 205, 'fried-rolls', true, 8, false, false, false),
('فولكانو فيلادلفيا', 'Volcano Philadelphia', 'Вулкан Филадельфия', 350, 'fried-rolls', true, 9, false, false, false),
('ساكي سان هوت', 'Sake San Hot Roll', 'Саке Сан хот', 270, 'fried-rolls', true, 10, false, false, false),
('صحراء سلمون', 'Sahara Roll Salmon', 'Сахара с лососем', 230, 'fried-rolls', true, 11, false, false, false),
('تونا سان هوت', 'Tuna San Hot Roll', 'Туна Сан хот', 235, 'fried-rolls', true, 12, false, false, false),
('أكينو هوت', 'Akeno Hot Roll', 'Акено хот', 280, 'fried-rolls', true, 13, false, false, false),
('أياشي', 'Ayashi Roll', 'Аяши', 350, 'fried-rolls', true, 14, false, false, false),
('كرانشي تونة', 'Crunchy Tuna Roll', 'Хрустящий тунец', 270, 'fried-rolls', true, 15, false, false, false),
('كرانشي جمبري هوت', 'Crunchy Shrimp Hot Roll', 'Хрустящая креветка хот', 240, 'fried-rolls', true, 16, false, false, false),
('دبل سلمون', 'Double Salmon Roll', 'Двойной лосось', 350, 'cooked-rolls', true, 1, false, false, false),
('كراكر', 'Cracker Roll', 'Крекер', 310, 'cooked-rolls', true, 2, false, false, false),
('زين', 'Zen Roll', 'Дзен', 320, 'cooked-rolls', true, 3, false, false, false),
('موناليزا', 'Mona Lisa Roll', 'Мона Лиза', 350, 'cooked-rolls', true, 4, false, false, false),
('ساكي', 'Saki Roll', 'Саки', 340, 'cooked-rolls', true, 5, false, false, false),
('فينوم مقلي', 'Vienom Fried Roll', 'Вьеном жареный', 320, 'cooked-rolls', true, 6, false, false, false),
('لافا مقلي', 'Lava Fried Roll', 'Лава жареный', 350, 'cooked-rolls', true, 7, false, false, false),
('جوهرة', 'Jewel Roll', 'Джуэл', 300, 'cooked-rolls', true, 8, false, false, false),
('فلامينج', 'Flaming Roll', 'Флейминг', 320, 'cooked-rolls', true, 9, false, false, false),
('توبيكو', 'Tobiko Roll', 'Тобико', 330, 'cooked-rolls', true, 10, false, false, false),
('هوسوماكي كافيار', 'Hosomaki Caviar', 'Хосомаки икра', 220, 'hosomaki', true, 1, false, false, false),
('هوسوماكي خيار', 'Hosomaki Cucumber', 'Хосомаки огурец', 80, 'hosomaki', true, 2, false, false, false),
('هوسوماكي رنجة', 'Hosomaki with Herring', 'Хосомаки селёдка', 220, 'hosomaki', true, 3, false, false, false),
('هوسوماكي سلمون', 'Hosomaki Salmon', 'Хосомаки лосось', 220, 'hosomaki', true, 4, false, false, false),
('هوسوماكي جمبري', 'Hosomaki Shrimp', 'Хосомаки креветка', 220, 'hosomaki', true, 5, false, false, false),
('هوسوماكي أنقليس', 'Hosomaki Eel', 'Хосомаки угорь', 190, 'hosomaki', true, 6, false, false, false),
('هوسوماكي كابوريا', 'Hosomaki Crab', 'Хосомаки краб', 150, 'hosomaki', true, 7, false, false, false),
('هوسوماكي أفوكادو', 'Hosomaki Avocado', 'Хосомаки авокадо', 130, 'hosomaki', true, 8, false, false, false),
('هوسوماكي تونة', 'Hosomaki Tuna', 'Хосомаки тунец', 220, 'hosomaki', true, 9, false, false, false),
('نيجيري أخطبوط', 'Nigiri Octopus', 'Нигири осьминог', 50, 'nigiri-temaki-sashimi', true, 1, false, false, false),
('نيجيري تونة', 'Nigiri Tuna', 'Нигири тунец', 50, 'nigiri-temaki-sashimi', true, 2, false, false, false),
('نيجيري سلمون', 'Nigiri Salmon', 'Нигири лосось', 50, 'nigiri-temaki-sashimi', true, 3, false, false, false),
('نيجيري جمبري', 'Nigiri Shrimp', 'Нигири креветка', 50, 'nigiri-temaki-sashimi', true, 4, false, false, false),
('نيجيري كابوريا', 'Nigiri Crab', 'Нигири краб', 50, 'nigiri-temaki-sashimi', true, 5, false, false, false),
('جمبري تمبورا', 'Shrimp Tempura', 'Креветка темпура', 50, 'nigiri-temaki-sashimi', true, 6, false, false, false),
('نيجيري أنقليس', 'Nigiri Eel', 'Нигири угорь', 50, 'nigiri-temaki-sashimi', true, 7, false, false, false)
) AS v(name_ar, name_en, name_ru, price, category, is_available, sort_order, is_new, is_popular, is_offer)
JOIN soshi.categories c ON c.slug = v.category;